services:
  - type: web
    name: priorities-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        sync: false        # nastavíš ručně v Renderu
      - key: SECRET_KEY
        generateValue: true